# Generated by Django 6.0.4 on 2026-04-19 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_private',
            field=models.BooleanField(default=False, help_text='Make your account private'),
        ),
        migrations.AddField(
            model_name='user',
            name='real_name',
            field=models.CharField(blank=True, help_text='Your real name (optional)', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='website',
            field=models.URLField(blank=True, help_text='Your personal website or portfolio'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
